# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SysOption.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptionDialog(object):
    def setupUi(self, OptionDialog):
        OptionDialog.setObjectName("OptionDialog")
        OptionDialog.resize(400, 300)
        self.verticalLayoutWidget = QtWidgets.QWidget(OptionDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 351, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.normalGroup = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.normalGroup.setObjectName("normalGroup")
        self.connectionGroup = QtWidgets.QGroupBox(self.normalGroup)
        self.connectionGroup.setGeometry(QtCore.QRect(0, 120, 349, 112))
        self.connectionGroup.setObjectName("connectionGroup")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.connectionGroup)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 331, 80))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkConn = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.checkConn.setObjectName("checkConn")
        self.horizontalLayout.addWidget(self.checkConn)
        self.checkBtn = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.checkBtn.setObjectName("checkBtn")
        self.horizontalLayout.addWidget(self.checkBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.infoUsr = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.infoUsr.setObjectName("infoUsr")
        self.horizontalLayout_2.addWidget(self.infoUsr)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.normalGroup)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(OptionDialog)
        QtCore.QMetaObject.connectSlotsByName(OptionDialog)

    def retranslateUi(self, OptionDialog):
        _translate = QtCore.QCoreApplication.translate
        OptionDialog.setWindowTitle(_translate("OptionDialog", "옵션"))
        self.normalGroup.setTitle(_translate("OptionDialog", "일반"))
        self.connectionGroup.setTitle(_translate("OptionDialog", "연결 설정"))
        self.checkConn.setText(_translate("OptionDialog", "서버 연결확인"))
        self.checkBtn.setText(_translate("OptionDialog", "확인"))
        self.infoUsr.setText(_translate("OptionDialog", "로그인 정보.."))
